<?php
/**
 * Property-Based Tests: Aggregate Payload Contains No PII
 *
 * **Validates: Requirements 4.5, 10.4**
 *
 * Property 4: For all payloads generated by AggregateExporter, no field
 * contains PII data (names, NIM, phone numbers, emails, borrowing history).
 *
 * Formal: ∀ payload ∈ generatedPayloads: extractFields(payload) ∩ PII_FIELDS == ∅
 *
 * This test simulates property-based testing by generating many random
 * combinations of inputs and verifying the property holds universally.
 *
 * Also covers Property 13 (PII Sanitization Completeness) for EnhancedExporter.
 *
 * @package NextLib\Agent\Tests
 */

namespace NextLib\Agent\Tests;

use PHPUnit\Framework\TestCase;
use NextLibAgent\Exporter\AggregateExporter;
use NextLibAgent\Exporter\EnhancedExporter;
use NextLibAgent\Exporter\MetricsCollector;
use NextLibAgent\Exporter\AnomalyTagger;
use NextLibAgent\Exporter\RetryScheduler;
use NextLibAgent\lib\HttpClient;
use PDO;

class PiiPropertyTest extends TestCase
{
    /**
     * @var PDO In-memory SQLite database
     */
    private $db;

    /**
     * @var HttpClient|\PHPUnit\Framework\MockObject\MockObject
     */
    private $httpClient;

    /**
     * Number of random iterations for property tests.
     */
    const ITERATIONS = 100;

    /**
     * Sample PII data used to inject and detect leaks.
     */
    const PII_EMAILS = array(
        'student@university.ac.id',
        'john.doe@gmail.com',
        'admin@univ.edu',
        'budi.santoso@campus.ac.id',
        'test+user@example.co.id',
    );

    const PII_PHONES = array(
        '+6281234567890',
        '08123456789',
        '0812 3456 7890',
        '+62-812-3456-7890',
        '021-555-12345',
    );

    const PII_NAMES = array(
        'Muhammad Rizky Pratama Putra',
        'Siti Nurhaliza Binti Ahmad',
        'John William Smith Junior',
        'Maria Christina Dewi Sartika',
        'Budi Setiawan Putra Utama',
    );

    const PII_NIMS = array(
        '20210001234',
        '19850012345',
        '2024567890123',
        '12345678',
        '20200099887',
    );

    protected function setUp(): void
    {
        $this->db = new PDO('sqlite::memory:');
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        $this->db->exec("
            CREATE TABLE visitor_count (
                visitor_id INTEGER PRIMARY KEY AUTOINCREMENT,
                member_id VARCHAR(20),
                member_name VARCHAR(100),
                checkin_date DATETIME NOT NULL
            )
        ");

        $this->db->exec("
            CREATE TABLE loan (
                loan_id INTEGER PRIMARY KEY AUTOINCREMENT,
                member_id VARCHAR(20),
                item_code VARCHAR(20),
                loan_date DATE NOT NULL,
                due_date DATE,
                return_date DATE
            )
        ");

        $this->httpClient = $this->createMock(HttpClient::class);
    }

    // =========================================================================
    // Property 4: buildPayload() output never contains PII
    // =========================================================================

    /**
     * **Validates: Requirements 4.5, 10.4**
     *
     * Property: For all random stats combinations, buildPayload() output
     * never contains PII patterns regardless of input values.
     *
     * @dataProvider randomStatsProvider
     */
    public function testBuildPayloadNeverContainsPII(
        int $visitorCount,
        int $loanCount,
        int $returnCount,
        string $tenantId,
        string $date
    ): void {
        $config = array('tenant_id' => $tenantId, 'cloud_base_url' => 'https://cloud.nextlib.id');
        $exporter = new AggregateExporter($this->db, $this->httpClient, $config);

        $stats = array(
            'visitor_count' => $visitorCount,
            'loan_count' => $loanCount,
            'return_count' => $returnCount,
        );

        $payload = $exporter->buildPayload($stats, $date);

        $this->assertFalse(
            AggregateExporter::containsPII($payload),
            sprintf(
                "buildPayload() produced PII for stats=[%d,%d,%d], tenant_id='%s', date='%s'. Payload: %s",
                $visitorCount,
                $loanCount,
                $returnCount,
                $tenantId,
                $date,
                json_encode($payload)
            )
        );
    }

    /**
     * Data provider that generates random stats combinations.
     *
     * @return array[]
     */
    public function randomStatsProvider(): array
    {
        $cases = array();
        $tenantFormats = $this->generateTenantIds();
        $dates = $this->generateDates();

        for ($i = 0; $i < self::ITERATIONS; $i++) {
            $visitorCount = mt_rand(0, 10000);
            $loanCount = mt_rand(0, 10000);
            $returnCount = mt_rand(0, 10000);
            $tenantId = $tenantFormats[array_rand($tenantFormats)];
            $date = $dates[array_rand($dates)];

            $cases["iteration_$i"] = array($visitorCount, $loanCount, $returnCount, $tenantId, $date);
        }

        return $cases;
    }

    // =========================================================================
    // Property 4: sanitizePayload() always produces PII-free output
    // =========================================================================

    /**
     * **Validates: Requirements 4.5, 10.4**
     *
     * Property: For all payloads (even those injected with PII),
     * sanitizePayload() output never contains PII.
     *
     * @dataProvider piiInjectedPayloadProvider
     */
    public function testSanitizePayloadAlwaysRemovesPII(array $dirtyPayload): void
    {
        $config = array('tenant_id' => 'test-tenant', 'cloud_base_url' => 'https://cloud.nextlib.id');
        $exporter = new AggregateExporter($this->db, $this->httpClient, $config);

        $sanitized = $exporter->sanitizePayload($dirtyPayload);

        $this->assertFalse(
            AggregateExporter::containsPII($sanitized),
            sprintf(
                "sanitizePayload() did not remove all PII. Input: %s, Output: %s",
                json_encode($dirtyPayload),
                json_encode($sanitized)
            )
        );
    }

    /**
     * Data provider that injects various PII patterns into payloads.
     *
     * @return array[]
     */
    public function piiInjectedPayloadProvider(): array
    {
        $cases = array();

        // Inject emails into tenant_id field
        foreach (self::PII_EMAILS as $i => $email) {
            $cases["email_in_tenant_id_$i"] = array(
                array(
                    'tenant_id' => $email,
                    'date' => '2026-06-12',
                    'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                    'sent_at' => '2026-06-12T23:59:00+07:00',
                ),
            );
        }

        // Inject phone numbers into tenant_id field
        foreach (self::PII_PHONES as $i => $phone) {
            $cases["phone_in_tenant_id_$i"] = array(
                array(
                    'tenant_id' => $phone,
                    'date' => '2026-06-12',
                    'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                    'sent_at' => '2026-06-12T23:59:00+07:00',
                ),
            );
        }

        // Inject names into tenant_id field
        foreach (self::PII_NAMES as $i => $name) {
            $cases["name_in_tenant_id_$i"] = array(
                array(
                    'tenant_id' => $name,
                    'date' => '2026-06-12',
                    'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                    'sent_at' => '2026-06-12T23:59:00+07:00',
                ),
            );
        }

        // Inject NIM numbers into tenant_id field
        foreach (self::PII_NIMS as $i => $nim) {
            $cases["nim_in_tenant_id_$i"] = array(
                array(
                    'tenant_id' => $nim,
                    'date' => '2026-06-12',
                    'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                    'sent_at' => '2026-06-12T23:59:00+07:00',
                ),
            );
        }

        // Inject PII into extra fields (should be stripped by sanitize)
        $cases['extra_email_field'] = array(
            array(
                'tenant_id' => 'valid-uuid',
                'date' => '2026-06-12',
                'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                'sent_at' => '2026-06-12T23:59:00+07:00',
                'email' => 'leak@example.com',
            ),
        );

        $cases['extra_name_field'] = array(
            array(
                'tenant_id' => 'valid-uuid',
                'date' => '2026-06-12',
                'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                'sent_at' => '2026-06-12T23:59:00+07:00',
                'member_name' => 'Muhammad Rizky Pratama Putra',
            ),
        );

        $cases['extra_phone_field'] = array(
            array(
                'tenant_id' => 'valid-uuid',
                'date' => '2026-06-12',
                'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                'sent_at' => '2026-06-12T23:59:00+07:00',
                'phone' => '+6281234567890',
            ),
        );

        $cases['extra_nim_field'] = array(
            array(
                'tenant_id' => 'valid-uuid',
                'date' => '2026-06-12',
                'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                'sent_at' => '2026-06-12T23:59:00+07:00',
                'nim' => '20210001234',
            ),
        );

        $cases['pii_in_stats_extra_keys'] = array(
            array(
                'tenant_id' => 'valid-uuid',
                'date' => '2026-06-12',
                'stats' => array(
                    'visitor_count' => 10,
                    'loan_count' => 5,
                    'return_count' => 3,
                    'borrower_email' => 'student@uni.ac.id',
                    'member_names' => 'John William Smith Junior',
                ),
                'sent_at' => '2026-06-12T23:59:00+07:00',
            ),
        );

        return $cases;
    }

    // =========================================================================
    // Property 4: containsPII() catches all known PII patterns
    // =========================================================================

    /**
     * **Validates: Requirements 4.5, 10.4**
     *
     * Property: containsPII() detects injected PII values (emails, phone
     * numbers, names, NIMs) reliably across all sample data.
     *
     * @dataProvider knownPiiDataProvider
     */
    public function testContainsPIIDetectsAllKnownPatterns(string $piiValue, string $piiType): void
    {
        $payload = array('field' => $piiValue);

        $this->assertTrue(
            AggregateExporter::containsPII($payload),
            sprintf(
                "containsPII() failed to detect %s: '%s'",
                $piiType,
                $piiValue
            )
        );
    }

    /**
     * Data provider with all known PII patterns that must be detected.
     *
     * @return array[]
     */
    public function knownPiiDataProvider(): array
    {
        $cases = array();

        foreach (self::PII_EMAILS as $i => $email) {
            $cases["email_$i"] = array($email, 'email');
        }

        foreach (self::PII_PHONES as $i => $phone) {
            $cases["phone_$i"] = array($phone, 'phone');
        }

        foreach (self::PII_NAMES as $i => $name) {
            $cases["name_$i"] = array($name, 'name (4+ words)');
        }

        foreach (self::PII_NIMS as $i => $nim) {
            $cases["nim_$i"] = array($nim, 'NIM/student ID');
        }

        return $cases;
    }

    // =========================================================================
    // Property 4: sanitizePayload() strips fields not in allowed list
    // =========================================================================

    /**
     * **Validates: Requirements 4.5, 10.4**
     *
     * Property: For all payloads with random extra keys, sanitizePayload()
     * output only contains keys from the allowed list.
     *
     * @dataProvider randomExtraFieldsProvider
     */
    public function testSanitizePayloadStripsNonAllowedFields(array $extraFields): void
    {
        $config = array('tenant_id' => 'test-tenant', 'cloud_base_url' => 'https://cloud.nextlib.id');
        $exporter = new AggregateExporter($this->db, $this->httpClient, $config);

        $payload = array_merge(
            array(
                'tenant_id' => 'valid-uuid',
                'date' => '2026-06-12',
                'stats' => array('visitor_count' => 10, 'loan_count' => 5, 'return_count' => 3),
                'sent_at' => '2026-06-12T23:59:00+07:00',
            ),
            $extraFields
        );

        $sanitized = $exporter->sanitizePayload($payload);

        $allowedTopKeys = array('tenant_id', 'date', 'stats', 'sent_at');
        $allowedStatsKeys = array('visitor_count', 'loan_count', 'return_count');

        // Verify only allowed top-level keys remain
        foreach (array_keys($sanitized) as $key) {
            $this->assertContains(
                $key,
                $allowedTopKeys,
                "Unexpected key '$key' found in sanitized payload. Extra fields: " . json_encode($extraFields)
            );
        }

        // Verify only allowed stats keys remain
        if (isset($sanitized['stats']) && is_array($sanitized['stats'])) {
            foreach (array_keys($sanitized['stats']) as $key) {
                $this->assertContains(
                    $key,
                    $allowedStatsKeys,
                    "Unexpected stats key '$key' found in sanitized payload."
                );
            }
        }
    }

    /**
     * Data provider that generates random extra field combinations.
     *
     * @return array[]
     */
    public function randomExtraFieldsProvider(): array
    {
        $cases = array();

        $extraKeyPool = array(
            'member_name', 'email', 'phone', 'nim', 'address',
            'borrowing_history', 'full_name', 'student_id',
            'ip_address', 'password', 'ssn', 'credit_card',
            'mother_maiden_name', 'date_of_birth', 'home_address',
        );

        $extraValuePool = array(
            'student@example.com',
            '+6281234567890',
            'Muhammad Rizky Pratama Putra',
            '20210001234',
            'Jl. Merdeka No. 123 RT01/RW02',
            array('book1', 'book2', 'book3'),
            true,
            12345,
            null,
        );

        for ($i = 0; $i < self::ITERATIONS; $i++) {
            $numExtras = mt_rand(1, 5);
            $extra = array();
            for ($j = 0; $j < $numExtras; $j++) {
                $key = $extraKeyPool[array_rand($extraKeyPool)];
                $value = $extraValuePool[array_rand($extraValuePool)];
                $extra[$key] = $value;
            }
            $cases["random_extras_$i"] = array($extra);
        }

        return $cases;
    }

    // =========================================================================
    // Property 4: Full pipeline (buildPayload → sanitizePayload) produces no PII
    // =========================================================================

    /**
     * **Validates: Requirements 4.5, 10.4**
     *
     * Property: The complete export pipeline (collectDailyStats → buildPayload
     * → sanitizePayload) never produces output containing PII, regardless of
     * what PII data exists in the database.
     */
    public function testFullPipelineNeverLeaksPIIFromDatabase(): void
    {
        $config = array('tenant_id' => 'campus-uuid-abc', 'cloud_base_url' => 'https://cloud.nextlib.id');
        $exporter = new AggregateExporter($this->db, $this->httpClient, $config);

        // Insert visitors with PII in the database (names, member IDs)
        $piiNames = array(
            'Muhammad Rizky Pratama Putra',
            'Siti Nurhaliza Binti Ahmad',
            'John William Smith Junior',
        );

        $piiMemberIds = array('20210001234', '19850012345', '2024567890123');

        $today = date('Y-m-d');
        foreach ($piiNames as $i => $name) {
            $stmt = $this->db->prepare(
                "INSERT INTO visitor_count (member_id, member_name, checkin_date) VALUES (:mid, :name, :date)"
            );
            $stmt->execute(array(
                'mid' => $piiMemberIds[$i],
                'name' => $name,
                'date' => $today . ' 0' . $i . ':00:00',
            ));
        }

        // Insert loans with PII member_ids
        foreach ($piiMemberIds as $mid) {
            $stmt = $this->db->prepare(
                "INSERT INTO loan (member_id, item_code, loan_date, due_date) VALUES (:mid, :item, :loan, :due)"
            );
            $stmt->execute(array(
                'mid' => $mid,
                'item' => 'B' . mt_rand(10000, 99999),
                'loan' => $today,
                'due' => date('Y-m-d', strtotime('+14 days')),
            ));
        }

        // Run the full pipeline
        $stats = $exporter->collectDailyStats($today);
        $payload = $exporter->buildPayload($stats, $today);
        $sanitized = $exporter->sanitizePayload($payload);

        // Verify no PII leaked
        $this->assertFalse(
            AggregateExporter::containsPII($sanitized),
            "Full pipeline leaked PII from database. Output: " . json_encode($sanitized)
        );

        // Also verify the raw buildPayload output has no PII
        $this->assertFalse(
            AggregateExporter::containsPII($payload),
            "buildPayload() leaked PII from database. Output: " . json_encode($payload)
        );

        // Verify PII names do NOT appear in the JSON output
        $jsonOutput = json_encode($sanitized);
        foreach ($piiNames as $name) {
            $this->assertStringNotContainsString(
                $name,
                $jsonOutput,
                "PII name '$name' leaked into sanitized payload"
            );
        }

        foreach ($piiMemberIds as $mid) {
            $this->assertStringNotContainsString(
                $mid,
                $jsonOutput,
                "PII member_id '$mid' leaked into sanitized payload"
            );
        }
    }

    /**
     * **Validates: Requirements 4.5, 10.4**
     *
     * Property: For many random database states with PII, the pipeline
     * never produces PII in the output.
     */
    public function testPipelineWithRandomDatabaseStateNeverLeaksPII(): void
    {
        $config = array('tenant_id' => 'random-tenant', 'cloud_base_url' => 'https://cloud.nextlib.id');
        $exporter = new AggregateExporter($this->db, $this->httpClient, $config);

        $today = date('Y-m-d');

        // Run multiple iterations with random PII data in the database
        for ($iter = 0; $iter < 20; $iter++) {
            // Insert random number of visitors with PII names
            $numVisitors = mt_rand(0, 50);
            for ($i = 0; $i < $numVisitors; $i++) {
                $name = $this->generateRandomPIIName();
                $mid = $this->generateRandomNIM();
                $stmt = $this->db->prepare(
                    "INSERT INTO visitor_count (member_id, member_name, checkin_date) VALUES (:mid, :name, :date)"
                );
                $stmt->execute(array(
                    'mid' => $mid,
                    'name' => $name,
                    'date' => $today . ' ' . sprintf('%02d', mt_rand(0, 23)) . ':00:00',
                ));
            }

            // Insert random loans
            $numLoans = mt_rand(0, 30);
            for ($i = 0; $i < $numLoans; $i++) {
                $stmt = $this->db->prepare(
                    "INSERT INTO loan (member_id, item_code, loan_date, due_date) VALUES (:mid, :item, :loan, :due)"
                );
                $stmt->execute(array(
                    'mid' => $this->generateRandomNIM(),
                    'item' => 'B' . mt_rand(10000, 99999),
                    'loan' => $today,
                    'due' => date('Y-m-d', strtotime('+14 days')),
                ));
            }

            // Run pipeline
            $stats = $exporter->collectDailyStats($today);
            $payload = $exporter->buildPayload($stats, $today);
            $sanitized = $exporter->sanitizePayload($payload);

            $this->assertFalse(
                AggregateExporter::containsPII($sanitized),
                "Iteration $iter: Pipeline leaked PII. Output: " . json_encode($sanitized)
            );
        }
    }

    // =========================================================================
    // Helper methods for generating random test data
    // =========================================================================

    /**
     * Generate an array of tenant IDs in various formats (UUIDs, slugs).
     *
     * @return string[]
     */
    private function generateTenantIds(): array
    {
        $ids = array();

        // UUID format
        for ($i = 0; $i < 20; $i++) {
            $ids[] = sprintf(
                '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
                mt_rand(0, 0xffff), mt_rand(0, 0xffff),
                mt_rand(0, 0xffff),
                mt_rand(0, 0x0fff) | 0x4000,
                mt_rand(0, 0x3fff) | 0x8000,
                mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
            );
        }

        // Slug format
        $slugPrefixes = array('univ', 'campus', 'lib', 'inst', 'polytechnic');
        $slugSuffixes = array('jakarta', 'bandung', 'surabaya', 'yogya', 'medan');
        for ($i = 0; $i < 10; $i++) {
            $ids[] = $slugPrefixes[array_rand($slugPrefixes)] . '-' . $slugSuffixes[array_rand($slugSuffixes)] . '-' . mt_rand(1, 99);
        }

        // Short IDs
        for ($i = 0; $i < 5; $i++) {
            $ids[] = 'tenant-' . mt_rand(1, 9999);
        }

        return $ids;
    }

    /**
     * Generate an array of dates in various formats.
     *
     * @return string[]
     */
    private function generateDates(): array
    {
        $dates = array();

        // Current/recent dates
        for ($i = 0; $i < 15; $i++) {
            $offset = mt_rand(0, 365);
            $dates[] = date('Y-m-d', strtotime("-$offset days"));
        }

        // Edge dates
        $dates[] = '2020-01-01';
        $dates[] = '2025-12-31';
        $dates[] = '2026-02-28';
        $dates[] = '2024-02-29'; // Leap year
        $dates[] = '2030-06-15';

        return $dates;
    }

    /**
     * Generate a random PII-like name (4+ words).
     *
     * @return string
     */
    private function generateRandomPIIName(): string
    {
        $firstNames = array('Muhammad', 'Siti', 'John', 'Maria', 'Budi', 'Ahmad', 'Dewi', 'Andi');
        $middleNames = array('Rizky', 'Nur', 'William', 'Christina', 'Putra', 'Bin', 'Sri', 'Dwi');
        $lastNames = array('Pratama', 'Haliza', 'Smith', 'Sartika', 'Setiawan', 'Rahman', 'Wati', 'Kurniawan');
        $suffixes = array('Putra', 'Junior', 'Utama', 'Nusantara', 'Sakti', 'Jaya', 'Mandiri', 'Sejahtera');

        return $firstNames[array_rand($firstNames)] . ' '
            . $middleNames[array_rand($middleNames)] . ' '
            . $lastNames[array_rand($lastNames)] . ' '
            . $suffixes[array_rand($suffixes)];
    }

    /**
     * Generate a random NIM/student ID (8+ digits).
     *
     * @return string
     */
    private function generateRandomNIM(): string
    {
        $year = mt_rand(2015, 2026);
        $dept = mt_rand(10, 99);
        $seq = mt_rand(1000, 9999);
        return $year . $dept . $seq;
    }

    // =========================================================================
    // Property 13: PII Sanitization Completeness — EnhancedExporter
    // =========================================================================

    /**
     * Create a minimal EnhancedExporter instance for PII sanitization tests.
     * Uses in-memory SQLite with all required SLiMS tables.
     *
     * @return EnhancedExporter
     */
    private function createEnhancedExporter(): EnhancedExporter
    {
        // EnhancedExporter needs a DB with all SLiMS tables for MetricsCollector/AnomalyTagger
        $db = new PDO('sqlite::memory:');
        $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        $db->exec("CREATE TABLE visitor_count (id INTEGER PRIMARY KEY, member_id INTEGER, checkin_date DATETIME)");
        $db->exec("CREATE TABLE loan (loan_id INTEGER PRIMARY KEY, member_id INTEGER, loan_date DATE, return_date DATE, due_date DATE, is_lent INTEGER DEFAULT 1, is_return INTEGER DEFAULT 0)");
        $db->exec("CREATE TABLE member (member_id INTEGER PRIMARY KEY, register_date DATE, expire_date DATE)");
        $db->exec("CREATE TABLE biblio (biblio_id INTEGER PRIMARY KEY, input_date DATE)");
        $db->exec("CREATE TABLE item (item_id INTEGER PRIMARY KEY, input_date DATE)");
        $db->exec("CREATE TABLE fines (fines_id INTEGER PRIMARY KEY, fines_date DATE, debet INTEGER DEFAULT 0, credit INTEGER DEFAULT 0)");
        $db->exec("CREATE TABLE reserve (reserve_id INTEGER PRIMARY KEY, reserve_date DATE)");

        $tempDir = sys_get_temp_dir() . '/pii_prop_test_' . getmypid() . '_' . mt_rand();
        mkdir($tempDir, 0755, true);

        $collector     = new MetricsCollector($db);
        $anomalyTagger = new AnomalyTagger($db, $collector);
        $retryScheduler = new RetryScheduler($tempDir);
        $httpClient    = $this->createMock(HttpClient::class);

        $config = array(
            'tenant_id'      => 'test-tenant-uuid',
            'cloud_base_url' => 'https://cloud.nextlib.test',
            'api_secret'     => 'test-secret-key',
            'v2_enabled'     => false,
            'export_schedule' => 'daily',
        );

        return new EnhancedExporter(
            $collector,
            $anomalyTagger,
            $retryScheduler,
            $httpClient,
            $config,
            $tempDir
        );
    }

    /**
     * Generate random PII values to inject into payloads.
     * Returns an array of [fieldKey => piiValue] pairs.
     *
     * @return array
     */
    private function generateRandomPIIInjection(): array
    {
        $piiPool = array(
            // Emails
            array('injected_email', 'student@university.ac.id'),
            array('injected_email', 'john.doe@gmail.com'),
            array('injected_email', 'budi.santoso@campus.ac.id'),
            array('injected_email', 'admin@univ.edu'),
            array('injected_email', 'test+user@example.co.id'),
            // Phones
            array('injected_phone', '+6281234567890'),
            array('injected_phone', '08123456789'),
            array('injected_phone', '0812 3456 7890'),
            array('injected_phone', '+62-812-3456-7890'),
            array('injected_phone', '021-555-12345'),
            // NIMs (8+ consecutive digits)
            array('injected_nim', '20210001234'),
            array('injected_nim', '19850012345'),
            array('injected_nim', '2024567890123'),
            array('injected_nim', '12345678'),
            array('injected_nim', '20200099887'),
            // Multi-word names (>3 words)
            array('injected_name', 'Muhammad Rizky Pratama Putra'),
            array('injected_name', 'Siti Nurhaliza Binti Ahmad'),
            array('injected_name', 'John William Smith Junior'),
            array('injected_name', 'Maria Christina Dewi Sartika'),
            array('injected_name', 'Budi Setiawan Putra Utama'),
        );

        return $piiPool[array_rand($piiPool)];
    }

    /**
     * Feature: enhanced-agent-exporter, Property 13: PII Sanitization Completeness
     *
     * **Validates: Requirements 10.1, 10.3**
     *
     * Property 13: For random v1 payloads with injected PII patterns (emails,
     * phone numbers, NIM-like sequences, multi-word names), sanitizePayloadV1()
     * removes all PII — containsPII() returns false on the result.
     *
     * Minimum 100 iterations.
     */
    public function testEnhancedExporterSanitizeV1AlwaysRemovesPII(): void
    {
        $exporter = $this->createEnhancedExporter();

        $piiFields = array(
            // Emails
            'student@university.ac.id',
            'john.doe@gmail.com',
            'admin@univ.edu',
            'budi.santoso@campus.ac.id',
            'test+user@example.co.id',
            // Phones
            '+6281234567890',
            '08123456789',
            '0812 3456 7890',
            '+62-812-3456-7890',
            '021-555-12345',
            // NIMs
            '20210001234',
            '19850012345',
            '2024567890123',
            '12345678',
            '20200099887',
            // Names (>3 words)
            'Muhammad Rizky Pratama Putra',
            'Siti Nurhaliza Binti Ahmad',
            'John William Smith Junior',
            'Maria Christina Dewi Sartika',
            'Budi Setiawan Putra Utama',
        );

        $injectableTopLevelKeys = array('tenant_id', 'extra_field', 'member_name', 'email', 'phone', 'nim');
        $dates = $this->generateDates();

        for ($i = 0; $i < self::ITERATIONS; $i++) {
            $piiValue = $piiFields[array_rand($piiFields)];
            // Inject into tenant_id (most direct injection) and optionally an extra key
            $injectKey = $injectableTopLevelKeys[array_rand($injectableTopLevelKeys)];

            $dirtyPayload = array(
                'tenant_id' => ($injectKey === 'tenant_id') ? $piiValue : 'tenant-' . mt_rand(1, 9999),
                'date'      => $dates[array_rand($dates)],
                'stats'     => array(
                    'visitor_count' => mt_rand(0, 10000),
                    'loan_count'    => mt_rand(0, 10000),
                    'return_count'  => mt_rand(0, 10000),
                ),
                'sent_at'   => date('c'),
            );

            // Always inject PII in an extra field too (will be stripped as non-allowed key)
            if ($injectKey !== 'tenant_id') {
                $dirtyPayload[$injectKey] = $piiValue;
            }

            $sanitized = $exporter->sanitizePayloadV1($dirtyPayload);

            $this->assertFalse(
                EnhancedExporter::containsPII($sanitized),
                sprintf(
                    'Iteration %d: sanitizePayloadV1() did not remove PII. ' .
                    'Injected \'%s\' => \'%s\'. Input: %s, Output: %s',
                    $i,
                    $injectKey,
                    $piiValue,
                    json_encode($dirtyPayload),
                    json_encode($sanitized)
                )
            );
        }
    }

    /**
     * Feature: enhanced-agent-exporter, Property 13: PII Sanitization Completeness
     *
     * **Validates: Requirements 10.1, 10.3**
     *
     * Property 13: For random v2 payloads with injected PII patterns (emails,
     * phone numbers, NIM-like sequences, multi-word names), sanitizePayloadV2()
     * removes all PII — containsPII() returns false on the result.
     *
     * Minimum 100 iterations.
     */
    public function testEnhancedExporterSanitizeV2AlwaysRemovesPII(): void
    {
        $exporter = $this->createEnhancedExporter();

        $piiFields = array(
            // Emails
            'student@university.ac.id',
            'john.doe@gmail.com',
            'admin@univ.edu',
            'budi.santoso@campus.ac.id',
            'test+user@example.co.id',
            // Phones
            '+6281234567890',
            '08123456789',
            '0812 3456 7890',
            '+62-812-3456-7890',
            '021-555-12345',
            // NIMs
            '20210001234',
            '19850012345',
            '2024567890123',
            '12345678',
            '20200099887',
            // Names (>3 words)
            'Muhammad Rizky Pratama Putra',
            'Siti Nurhaliza Binti Ahmad',
            'John William Smith Junior',
            'Maria Christina Dewi Sartika',
            'Budi Setiawan Putra Utama',
        );

        $injectableTopLevelKeys = array('tenant_id', 'extra_field', 'member_name', 'email', 'phone', 'nim', 'schema_version');
        $dates = $this->generateDates();

        $dailyMetricKeys = array(
            'visitor_count', 'unique_visitor_count', 'loan_count', 'return_count',
            'new_member_count', 'new_biblio_count', 'new_item_count',
            'fines_debet_total', 'fines_credit_total', 'reservation_count',
        );
        $snapshotMetricKeys = array('total_collection_size', 'active_member_count', 'active_overdue_count');

        for ($i = 0; $i < self::ITERATIONS; $i++) {
            $piiValue = $piiFields[array_rand($piiFields)];
            $injectKey = $injectableTopLevelKeys[array_rand($injectableTopLevelKeys)];

            // Build base v2 payload with safe values
            $dailyMetrics = array();
            foreach ($dailyMetricKeys as $k) {
                $dailyMetrics[$k] = mt_rand(0, 10000);
            }
            $snapshotMetrics = array();
            foreach ($snapshotMetricKeys as $k) {
                $snapshotMetrics[$k] = mt_rand(0, 100000);
            }

            $dirtyPayload = array(
                'schema_version'   => '2.0',
                'tenant_id'        => 'tenant-' . mt_rand(1, 9999),
                'date'             => $dates[array_rand($dates)],
                'sent_at'          => date('c'),
                'daily_metrics'    => $dailyMetrics,
                'snapshot_metrics' => $snapshotMetrics,
                'anomaly_flags'    => array(),
            );

            // Inject PII into chosen field
            if ($injectKey === 'tenant_id') {
                $dirtyPayload['tenant_id'] = $piiValue;
            } elseif ($injectKey === 'schema_version') {
                // Inject into schema_version (allowed key but should be sanitized if PII)
                $dirtyPayload['schema_version'] = $piiValue;
            } else {
                // Inject into a non-allowed key (will be stripped)
                $dirtyPayload[$injectKey] = $piiValue;
            }

            $sanitized = $exporter->sanitizePayloadV2($dirtyPayload);

            $this->assertFalse(
                EnhancedExporter::containsPII($sanitized),
                sprintf(
                    'Iteration %d: sanitizePayloadV2() did not remove PII. ' .
                    'Injected \'%s\' => \'%s\'. Input: %s, Output: %s',
                    $i,
                    $injectKey,
                    $piiValue,
                    json_encode($dirtyPayload),
                    json_encode($sanitized)
                )
            );
        }
    }
}
